### ISSUE TITLE
Some classes depreciated 

### ISSUE THREAD

**Issue by GriffinWilcox** [TeamFusion364/PracticalNeoSwerve#1]
I was trying to use this code for our mk4s that just came in but some of the classes namly SparkMaxPidController and a few others became depreciated and im not sure what to replace them with if you could help or provide a email we could talk through there.

**Comment by Breichen1** [comment]
We are in the process of updating the deprecated SparkMaxPIDController object. For now, the original SparkMax object still works as expected and we did not want to switch to the new SparkPIDController object until we become more familiar with how to properly utilize it. We will be pushing an update in the near future.

**Comment by Breichen1** [comment]
> I was trying to use this code for our mk4s that just came in but some of the classes namly SparkMaxPidController and a few others became depreciated and im not sure what to replace them with if you could help or provide a email we could talk through there.

We are in the process of updating the deprecated SparkMaxPIDController object. For now, the original SparkMax object still works as expected and we did not want to switch to the new SparkPIDController object until we become more familiar with how to properly utilize it. We will be pushing an update in the near future.

**Comment by Breichen1** [comment]
For the moment, I have pushed some code that replaces all instances of `SparkMaxPIDController` with the new `SparkPIDController`, which should (*potentially, and untested as of right now*) make  this code compatible with NEO Vortex motors and get rid of those deprecation warnings. This code is still on phoenix 5, so the CTRE Deprecations will persist, but for the 2024 season Phoenix 5 is still supported so we will be updating this repository to Phoenix 6 after the competition season.
